// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using libraryproject.Data;

#nullable disable

namespace libraryproject.Migrations
{
    [DbContext(typeof(QLTVContext))]
    partial class QLTVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("libraryproject.Models.BoSuuTap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBoSuuTap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("BoSuuTaps");
                });

            modelBuilder.Entity("libraryproject.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhieuMuonID")
                        .HasColumnType("int");

                    b.Property<int>("TaiLieuID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PhieuMuonID");

                    b.HasIndex("TaiLieuID");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("libraryproject.Models.LoaiBanDoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiBanDocs");
                });

            modelBuilder.Entity("libraryproject.Models.MaVach", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaBarcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiLieuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TaiLieuID");

                    b.ToTable("MaVachs");
                });

            modelBuilder.Entity("libraryproject.Models.NguoiDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeChuongTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiBanDocID")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBanDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nganh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThanhVien")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiBanDocID");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("libraryproject.Models.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("libraryproject.Models.PhieuMuon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhieuMuon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayHenTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("libraryproject.Models.TaiLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BoSuuTapID")
                        .HasColumnType("int");

                    b.Property<string>("Cutter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DDC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoGiay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Khoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyHieuKho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaXuatBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanDeSongSong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLuuTru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiXuatBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanConLaiNhanDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhuChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongHienCo")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongNhapVe")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinTrachNhiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThuatNguChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongSoTrang")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BoSuuTapID");

                    b.ToTable("TaiLieus");
                });

            modelBuilder.Entity("libraryproject.ThongBao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("libraryproject.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("libraryproject.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("PhieuMuonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("libraryproject.Models.TaiLieu", "TaiLieu")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("TaiLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("libraryproject.Models.MaVach", b =>
                {
                    b.HasOne("libraryproject.Models.TaiLieu", "TaiLieu")
                        .WithMany("MaVachs")
                        .HasForeignKey("TaiLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("libraryproject.Models.NguoiDung", b =>
                {
                    b.HasOne("libraryproject.Models.LoaiBanDoc", "LoaiBanDoc")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("LoaiBanDocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiBanDoc");
                });

            modelBuilder.Entity("libraryproject.Models.PhieuMuon", b =>
                {
                    b.HasOne("libraryproject.Models.NguoiDung", "NguoiDung")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("libraryproject.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("libraryproject.Models.TaiLieu", b =>
                {
                    b.HasOne("libraryproject.Models.BoSuuTap", "BoSuuTap")
                        .WithMany("TaiLieus")
                        .HasForeignKey("BoSuuTapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoSuuTap");
                });

            modelBuilder.Entity("libraryproject.ThongBao", b =>
                {
                    b.HasOne("libraryproject.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("libraryproject.Models.BoSuuTap", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("libraryproject.Models.LoaiBanDoc", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("libraryproject.Models.NguoiDung", b =>
                {
                    b.Navigation("PhieuMuons");

                    b.Navigation("ThongBaos");
                });

            modelBuilder.Entity("libraryproject.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("libraryproject.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("libraryproject.Models.TaiLieu", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("MaVachs");
                });
#pragma warning restore 612, 618
        }
    }
}
